var wms_layers = [];


        var lyr_ESRISatellite_0 = new ol.layer.Tile({
            'title': 'ESRI Satellite',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
            })
        });
var format_HojadeclculosinttuloHoja1_1 = new ol.format.GeoJSON();
var features_HojadeclculosinttuloHoja1_1 = format_HojadeclculosinttuloHoja1_1.readFeatures(json_HojadeclculosinttuloHoja1_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_HojadeclculosinttuloHoja1_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_HojadeclculosinttuloHoja1_1.addFeatures(features_HojadeclculosinttuloHoja1_1);
var lyr_HojadeclculosinttuloHoja1_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_HojadeclculosinttuloHoja1_1, 
                style: style_HojadeclculosinttuloHoja1_1,
                interactive: true,
                title: '<img src="styles/legend/HojadeclculosinttuloHoja1_1.png" /> Hoja de cálculo sin título - Hoja 1'
            });

lyr_ESRISatellite_0.setVisible(true);lyr_HojadeclculosinttuloHoja1_1.setVisible(true);
var layersList = [lyr_ESRISatellite_0,lyr_HojadeclculosinttuloHoja1_1];
lyr_HojadeclculosinttuloHoja1_1.set('fieldAliases', {'N°': 'N°', 'Nombre': 'Nombre', 'Tipo de elemento (organización, persona)': 'Tipo de elemento (organización, persona)', 'Esfera que representa (Actor público, privado, sociedad civil)': 'Esfera que representa (Actor público, privado, sociedad civil)', 'Categoría actor 1': 'Categoría actor 1', 'Categoría actor 2': 'Categoría actor 2', 'Organizaciones que participa/representa': 'Organizaciones que participa/representa', 'Cargo (s)': 'Cargo (s)', 'Comentarios internos': 'Comentarios internos', 'Descripción': 'Descripción', 'Ámbito': 'Ámbito', 'Región': 'Región', 'Comuna': 'Comuna', 'Sector': 'Sector', 'Dirección/punto de referencia acordada entrevistado': 'Dirección/punto de referencia acordada entrevistado', 'Latitud': 'Latitud', 'Longitud': 'Longitud', 'Impacto del proyecto': 'Impacto del proyecto', 'Posición respecto a proteger': 'Posición respecto a proteger', 'Posición respecto al proyecto': 'Posición respecto al proyecto', 'Potencial vínculo con el proyecto 1': 'Potencial vínculo con el proyecto 1', 'Potencial vínculo con el proyecto 2': 'Potencial vínculo con el proyecto 2', 'Oportunidades de relacionamiento (descripción potencial vínculo)': 'Oportunidades de relacionamiento (descripción potencial vínculo)', 'Proyecto-eje de relacionamiento comunitario vinculado': 'Proyecto-eje de relacionamiento comunitario vinculado', 'Intereses del actor/organización (detalle descriptivo categoría de intereses)': 'Intereses del actor/organización (detalle descriptivo categoría de intereses)', 'Emprendimiento': 'Emprendimiento', 'Turismo': 'Turismo', 'Identidad local': 'Identidad local', 'Vivienda y regularización de tierras': 'Vivienda y regularización de tierras', 'Acceso a SSBB': 'Acceso a SSBB', 'Conectividad': 'Conectividad', 'Educación': 'Educación', 'Salud': 'Salud', 'Medio Ambiente': 'Medio Ambiente', 'Riesgo de desastre': 'Riesgo de desastre', 'Contacto': 'Contacto', '¿Entrevistado?': '¿Entrevistado?', '¿Entrevista clave a transcribir?': '¿Entrevista clave a transcribir?', 'Reuniones previas': 'Reuniones previas', 'Avanzada exploratoria': 'Avanzada exploratoria', 'Avanzada 1': 'Avanzada 1', 'Avanzada 2': 'Avanzada 2', 'Avanzada 3': 'Avanzada 3', 'Avanzada 4': 'Avanzada 4', 'Link doc apuntes': 'Link doc apuntes', 'Encargado traspaso apuntes': 'Encargado traspaso apuntes', 'Link grabación': 'Link grabación', 'Link a transcripción': 'Link a transcripción', 'Encargado transcripción': 'Encargado transcripción', 'Tiempos': 'Tiempos', 'Minutos totales transcrito': 'Minutos totales transcrito', 'Estado': 'Estado', });
lyr_HojadeclculosinttuloHoja1_1.set('fieldImages', {'N°': 'Range', 'Nombre': 'TextEdit', 'Tipo de elemento (organización, persona)': 'TextEdit', 'Esfera que representa (Actor público, privado, sociedad civil)': 'TextEdit', 'Categoría actor 1': 'TextEdit', 'Categoría actor 2': 'TextEdit', 'Organizaciones que participa/representa': 'TextEdit', 'Cargo (s)': 'TextEdit', 'Comentarios internos': 'TextEdit', 'Descripción': 'TextEdit', 'Ámbito': 'TextEdit', 'Región': 'TextEdit', 'Comuna': 'TextEdit', 'Sector': 'TextEdit', 'Dirección/punto de referencia acordada entrevistado': 'TextEdit', 'Latitud': 'TextEdit', 'Longitud': 'TextEdit', 'Impacto del proyecto': 'TextEdit', 'Posición respecto a proteger': 'TextEdit', 'Posición respecto al proyecto': 'TextEdit', 'Potencial vínculo con el proyecto 1': 'TextEdit', 'Potencial vínculo con el proyecto 2': 'TextEdit', 'Oportunidades de relacionamiento (descripción potencial vínculo)': 'TextEdit', 'Proyecto-eje de relacionamiento comunitario vinculado': 'TextEdit', 'Intereses del actor/organización (detalle descriptivo categoría de intereses)': 'TextEdit', 'Emprendimiento': 'TextEdit', 'Turismo': 'TextEdit', 'Identidad local': 'CheckBox', 'Vivienda y regularización de tierras': 'TextEdit', 'Acceso a SSBB': 'TextEdit', 'Conectividad': 'CheckBox', 'Educación': 'CheckBox', 'Salud': 'CheckBox', 'Medio Ambiente': 'TextEdit', 'Riesgo de desastre': 'TextEdit', 'Contacto': 'TextEdit', '¿Entrevistado?': 'TextEdit', '¿Entrevista clave a transcribir?': 'TextEdit', 'Reuniones previas': 'TextEdit', 'Avanzada exploratoria': 'TextEdit', 'Avanzada 1': 'TextEdit', 'Avanzada 2': 'TextEdit', 'Avanzada 3': 'TextEdit', 'Avanzada 4': 'TextEdit', 'Link doc apuntes': 'TextEdit', 'Encargado traspaso apuntes': 'TextEdit', 'Link grabación': 'TextEdit', 'Link a transcripción': 'TextEdit', 'Encargado transcripción': 'TextEdit', 'Tiempos': 'TextEdit', 'Minutos totales transcrito': 'TextEdit', 'Estado': 'TextEdit', });
lyr_HojadeclculosinttuloHoja1_1.set('fieldLabels', {'N°': 'inline label', 'Nombre': 'inline label', 'Tipo de elemento (organización, persona)': 'inline label', 'Esfera que representa (Actor público, privado, sociedad civil)': 'inline label', 'Categoría actor 1': 'inline label', 'Categoría actor 2': 'inline label', 'Organizaciones que participa/representa': 'inline label', 'Cargo (s)': 'inline label', 'Comentarios internos': 'inline label', 'Descripción': 'inline label', 'Ámbito': 'inline label', 'Región': 'inline label', 'Comuna': 'inline label', 'Sector': 'inline label', 'Dirección/punto de referencia acordada entrevistado': 'inline label', 'Latitud': 'inline label', 'Longitud': 'inline label', 'Impacto del proyecto': 'inline label', 'Posición respecto a proteger': 'inline label', 'Posición respecto al proyecto': 'inline label', 'Potencial vínculo con el proyecto 1': 'inline label', 'Potencial vínculo con el proyecto 2': 'inline label', 'Oportunidades de relacionamiento (descripción potencial vínculo)': 'inline label', 'Proyecto-eje de relacionamiento comunitario vinculado': 'inline label', 'Intereses del actor/organización (detalle descriptivo categoría de intereses)': 'inline label', 'Emprendimiento': 'inline label', 'Turismo': 'inline label', 'Identidad local': 'inline label', 'Vivienda y regularización de tierras': 'inline label', 'Acceso a SSBB': 'inline label', 'Conectividad': 'inline label', 'Educación': 'inline label', 'Salud': 'inline label', 'Medio Ambiente': 'inline label', 'Riesgo de desastre': 'inline label', 'Contacto': 'inline label', '¿Entrevistado?': 'inline label', '¿Entrevista clave a transcribir?': 'inline label', 'Reuniones previas': 'inline label', 'Avanzada exploratoria': 'inline label', 'Avanzada 1': 'inline label', 'Avanzada 2': 'inline label', 'Avanzada 3': 'inline label', 'Avanzada 4': 'inline label', 'Link doc apuntes': 'inline label', 'Encargado traspaso apuntes': 'inline label', 'Link grabación': 'inline label', 'Link a transcripción': 'inline label', 'Encargado transcripción': 'inline label', 'Tiempos': 'inline label', 'Minutos totales transcrito': 'inline label', 'Estado': 'inline label', });
lyr_HojadeclculosinttuloHoja1_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});